name: kingoflotto
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0

  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  fluttertoast: ^8.2.8
  google_mobile_ads: ^5.1.0
  http: ^1.2.2
  html: ^0.15.4
  flutter_cache_manager: ^3.4.0
  sqflite: ^2.3.3+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  firebase_crashlytics: ^4.0.4
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

  custom_lint:
  riverpod_generator: 2.3.3
  riverpod_lint: ^2.1.1
  json_serializable: ^6.8.0
  isar_generator: any
  analyzer: ^5.13.0






flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_ball.png"

flutter_native_splash:
  color: "#CECECE"
  #background_image: "assets/background.png"
  image: assets/images/launcher_ball.png
  #branding: assets/dart.png
  android_12:
    image: assets/images/splash_icon.png
    color: "#CECECE"
  #icon_background_color: "#111111"
  #branding: assets/dart.png
